// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWUIST1Hno5cUfAdzDscqq90jqiVrRUm0',
    appId: '1:265770618220:web:d6605792c6a647eadd7749',
    messagingSenderId: '265770618220',
    projectId: 'finalchatapp-11d54',
    authDomain: 'finalchatapp-11d54.firebaseapp.com',
    storageBucket: 'finalchatapp-11d54.appspot.com',
    measurementId: 'G-SY3HPELS3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4F0YdNv8ezlala9iosF2mpeJrbWvzlZM',
    appId: '1:265770618220:android:9c32ce41f60b98f0dd7749',
    messagingSenderId: '265770618220',
    projectId: 'finalchatapp-11d54',
    storageBucket: 'finalchatapp-11d54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTdAjtdGB19-5AUipyA-L_rQsjekDx8Mc',
    appId: '1:265770618220:ios:6143c965222d87b5dd7749',
    messagingSenderId: '265770618220',
    projectId: 'finalchatapp-11d54',
    storageBucket: 'finalchatapp-11d54.appspot.com',
    iosBundleId: 'com.example.finalChatApp',
  );
}
